FROM golang:alpine

RUN apk add protoc
RUN apk add git
RUN apk add --update alpine-sdk

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest