version: "3.7"

services:
  go:
    #image: golang:alpine
    build: ./file-server/.
    networks:
      fileserver_network:
        ipv4_address: 172.32.0.1
    ports:
      - 127.0.0.1:9010:9010
      - 50051:50051
    working_dir: /app
    environment:
      SERVER_ADDRESS: 172.32.0.1
      SERVER_PORT: 9010
      
    volumes:
      - ./:/app
    stdin_open: true
    tty: true

networks:
  fileserver_network:
    ipam:
      config:
        - gateway: 172.32.1.1
          subnet: 172.32.0.0/16
